### ISSUE TITLE
Not working with newest version of Dynmap and Quickshop

### ISSUE THREAD

**Issue by Bloodlex** [PotatoCraft-Studio/QuickShopDynmap#7]
`16.02 02:08:38 [Server] WARN [QuickShopDynmap] Plugin QuickShopDynmap v1.0 generated an exception while executing task 785
16.02 02:08:38 [Server] INFO java.lang.IllegalStateException: #[Illegal Access] This method require runs on server main thread.
16.02 02:08:38 [Server] INFO at org.maxgamer.quickshop.util.Util.ensureThread(Util.java:1557) ~[?:?]
16.02 02:08:38 [Server] INFO at org.maxgamer.quickshop.shop.ContainerShop.getRemainingStock(ContainerShop.java:888) ~[?:?]
16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap.updateMarkers(QuickShopDynmap.java:112) ~[?:?]
16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap.access$000(QuickShopDynmap.java:26) ~[?:?]
16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap$1.run(QuickShopDynmap.java:56) ~[?:?]
16.02 02:08:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-468]
16.02 02:08:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-468]
16.02 02:08:38 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-468]
16.02 02:08:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
16.02 02:08:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
16.02 02:08:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

Dynmap version: core=3.1-beta7-449, plugin=3.1-beta7-449
QuickShop Reremake Ver >> 4.0.7.3

**Comment by Ghost-chu** [comment]
Thanks for reporting but sorry I had no time to update that cause I'm in hospital with high-fever.



---Original---

**Comment by Bloodlex** [comment]
> Thanks for reporting but sorry I had no time to update that cause I'm in hospital with high-fever.
> […](#)
> ---Original--- From: "Bloodlex"<notifications@github.com&gt; Date: Tue, Feb 16, 2021 09:21 AM To: "Ghost-chu/QuickShopDynmap"<QuickShopDynmap@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [Ghost-chu/QuickShopDynmap] Not working with newest version of Dynmap and Quickshop (#7) 16.02 02:08:38 [Server] WARN [QuickShopDynmap] Plugin QuickShopDynmap v1.0 generated an exception while executing task 785 16.02 02:08:38 [Server] INFO java.lang.IllegalStateException: #[Illegal Access] This method require runs on server main thread. 16.02 02:08:38 [Server] INFO at org.maxgamer.quickshop.util.Util.ensureThread(Util.java:1557) ~[?:?] 16.02 02:08:38 [Server] INFO at org.maxgamer.quickshop.shop.ContainerShop.getRemainingStock(ContainerShop.java:888) ~[?:?] 16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap.updateMarkers(QuickShopDynmap.java:112) ~[?:?] 16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap.access$000(QuickShopDynmap.java:26) ~[?:?] 16.02 02:08:38 [Server] INFO at com.mcsunnyside.quickshopdynmap.QuickShopDynmap$1.run(QuickShopDynmap.java:56) ~[?:?] 16.02 02:08:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-468] 16.02 02:08:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-468] 16.02 02:08:38 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-468] 16.02 02:08:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262] 16.02 02:08:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262] 16.02 02:08:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262] Dynmap version: core=3.1-beta7-449, plugin=3.1-beta7-449 QuickShop Reremake Ver &gt;&gt; 4.0.7.3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Oh... sorry to hear that! :( I hope you recover very soon and will be all right!

**Comment by Bloodlex** [comment]
Hello @Ghost-chu I see you've already committed to QuickShop repository, I hope it is all right on your end. Could you please take a look on that now if you can? 🙂

**Comment by Ghost-chu** [comment]
https://ci.codemc.io/job/Ghost-chu/view/QuickShop-Addons/job/QuickShopDynmap/3/artifact/target/QuickShop-Dynmap-1.0.jar

**Comment by Bloodlex** [comment]
> https://ci.codemc.io/job/Ghost-chu/view/QuickShop-Addons/job/QuickShopDynmap/3/artifact/target/QuickShop-Dynmap-1.0.jar

It works now! Thank you very much!! 🙂
